
# 1. CycleGan: use cycleGan to perform stylistic transitions between cityscape and foggy-cityscape to obtain enhanced datasets for both. (cityscape_fake, foggy-cityscape_fake)


# 2. Source Model: use the image (cityscape_fake) generated by CycleGAN in which content is cityscape and style is foggy-cityscape to train faster rcnn
# CUDA_VISIBLE_DEVICES=0 python faster_rcnn_train.py --dataset cs_cyclegan_fg --net vgg16 --bs 1 --lr 2e-3 --lr_decay_step 6 --epochs 10 --cuda


# 3. Pseudo Label: generate pseudo label for foggy-cityscape and save them to an xml file. The enhanced dataset foggy-cityscape_fake also uses these pseudo labels.
# CUDA_VISIBLE_DEVICES=0 python faster_rcnn_test.py --dataset foggy_cityscape --dataset_part train --model_dir './output/model/vgg16/cs_cyclegan_fg/faster_rcnn_1_7_5931.pth' --cuda --vis --savelabel


# 4. Mosaic Augment. Mosaic.py is in the directory lib/IDF
# python Mosaic.py


# 5. IDF train: use source domain（cityscape，cityscape_fake, augmentation）and target domain（foggy-cityscape， foggy-cityscape_fake, augmentation）to train model IDF.
# CUDA_VISIBLE_DEVICES=0 python IDF_train.py --dataset cs_combine_fg_combine_mosaic --dataset_t cs_fg_combine_cs_combine_mosaic --net vgg16 --log_ckpt_name cs_combine_fg_combine_mosaic2cs_fg_combine_cs_combine_mosaic

